# Generated by Django 5.2.15 on 2026-07-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('url', 'URL'), ('search', 'Search'), ('manual', 'Manual')], default='url', max_length=24)),
                ('value', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content_markdown', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='sources_doc_created_fdeca3_idx'), models.Index(fields=['embedding_id'], name='sources_doc_embeddi_925702_idx')],
            },
        ),
    ]
