// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AlertEvent = {
    readonly id: number;
    rule?: number | null;
    readonly rule_name: string;
    monitored_target?: number | null;
    event_type: EventTypeEnum;
    severity?: AlertEventSeverityEnum;
    title: string;
    message: string;
    payload?: unknown;
    delivered?: boolean;
    readonly created_at: string;
};

/**
 * * `info` - Info
 * * `medium` - Medium
 * * `high` - High
 */
export type AlertEventSeverityEnum = 'info' | 'medium' | 'high';

export type AlertRule = {
    readonly id: number;
    name: string;
    event_type: EventTypeEnum;
    conditions?: unknown;
    enabled?: boolean;
    monitored_target?: number | null;
    cooldown_minutes?: number;
    readonly last_triggered: string | null;
    readonly created_at: string;
    readonly updated_at: string;
};

export type CensorshipIncident = {
    readonly id: number;
    country_code: string;
    asn: string;
    target_domain: string;
    anomaly_type: string;
    measurement_count?: number;
    failure_rate?: number;
    readonly reported_at: string;
};

export type DarkWebCrawl = {
    readonly id: number;
    url: string;
    keywords?: string;
    readonly monitored_target: number | null;
    status: ProcessingStatusEnum;
    readonly routed_via_tor: boolean;
    readonly is_onion: boolean;
    readonly error: string;
    readonly results: unknown;
    readonly created_at: string;
    readonly updated_at: string;
};

export type Document = {
    readonly id: number;
    source: Source;
    url?: string | string;
    title?: string;
    content_markdown?: string;
    metadata?: unknown;
    embedding_id?: string;
    readonly created_at: string;
};

/**
 * * `relay_anomaly` - Relay anomaly
 * * `censorship` - Censorship incident
 * * `keyword_hit` - Crawler keyword hit
 * * `change` - Snapshot change
 */
export type EventTypeEnum = 'relay_anomaly' | 'censorship' | 'keyword_hit' | 'change';

export type IngestRequest = {
    urls: Array<string>;
    provider_preference?: Array<ProviderPreferenceEnum>;
    tags?: Array<string>;
    notify?: boolean;
    telegram_chat_id?: string;
};

export type IngestionJob = {
    readonly id: string;
    status?: ProcessingStatusEnum;
    provider_preference?: unknown;
    tags?: unknown;
    notification_settings?: unknown;
    error?: string;
    cost_metadata?: unknown;
    result_metadata?: unknown;
    readonly created_at: string;
    readonly updated_at: string;
    completed_at?: string | null;
    readonly targets: Array<JobTarget>;
};

export type JobTarget = {
    readonly id: number;
    url: string;
    status?: JobTargetStatusEnum;
    fetched_with?: string;
    document: Document;
    error?: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * * `queued` - Queued
 * * `fetched` - Fetched
 * * `failed` - Failed
 */
export type JobTargetStatusEnum = 'queued' | 'fetched' | 'failed';

export type MonitoredTarget = {
    readonly id: number;
    kind: MonitoredTargetKindEnum;
    value: string;
    /**
     * Seconds between scheduled checks.
     */
    interval?: number;
    enabled?: boolean;
    config?: unknown;
    readonly last_run: string | null;
    readonly next_run: string | null;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * * `username` - Username
 * * `domain` - Domain
 * * `ooni` - OONI domain
 * * `tor_relay` - Tor relay
 * * `onion` - Onion URL
 */
export type MonitoredTargetKindEnum = 'username' | 'domain' | 'ooni' | 'tor_relay' | 'onion';

export type OsintScan = {
    readonly id: number;
    target: string;
    scan_type: ScanTypeEnum;
    readonly monitored_target: number | null;
    status: ProcessingStatusEnum;
    readonly error: string;
    readonly results: unknown;
    readonly created_at: string;
    readonly updated_at: string;
};

export type PatchedAlertRule = {
    readonly id?: number;
    name?: string;
    event_type?: EventTypeEnum;
    conditions?: unknown;
    enabled?: boolean;
    monitored_target?: number | null;
    cooldown_minutes?: number;
    readonly last_triggered?: string | null;
    readonly created_at?: string;
    readonly updated_at?: string;
};

export type PatchedDarkWebCrawl = {
    readonly id?: number;
    url?: string;
    keywords?: string;
    readonly monitored_target?: number | null;
    status?: ProcessingStatusEnum;
    readonly routed_via_tor?: boolean;
    readonly is_onion?: boolean;
    readonly error?: string;
    readonly results?: unknown;
    readonly created_at?: string;
    readonly updated_at?: string;
};

export type PatchedMonitoredTarget = {
    readonly id?: number;
    kind?: MonitoredTargetKindEnum;
    value?: string;
    /**
     * Seconds between scheduled checks.
     */
    interval?: number;
    enabled?: boolean;
    config?: unknown;
    readonly last_run?: string | null;
    readonly next_run?: string | null;
    readonly created_at?: string;
    readonly updated_at?: string;
};

export type PatchedOsintScan = {
    readonly id?: number;
    target?: string;
    scan_type?: ScanTypeEnum;
    readonly monitored_target?: number | null;
    status?: ProcessingStatusEnum;
    readonly error?: string;
    readonly results?: unknown;
    readonly created_at?: string;
    readonly updated_at?: string;
};

/**
 * * `queued` - Queued
 * * `running` - Running
 * * `completed` - Completed
 * * `failed` - Failed
 */
export type ProcessingStatusEnum = 'queued' | 'running' | 'completed' | 'failed';

/**
 * * `firecrawl` - firecrawl
 * * `zenrows` - zenrows
 * * `bright_data` - bright_data
 * * `tinyfish` - tinyfish
 * * `direct` - direct
 */
export type ProviderPreferenceEnum = 'firecrawl' | 'zenrows' | 'bright_data' | 'tinyfish' | 'direct';

export type RelayAnomaly = {
    readonly id: number;
    fingerprint: string;
    nickname?: string;
    country_code?: string;
    country_name?: string;
    as_number?: string;
    latitude?: number | null;
    longitude?: number | null;
    metric?: string;
    anomaly_type?: string;
    score?: number;
    severity?: RelayAnomalySeverityEnum;
    detector?: string;
    detail?: unknown;
    readonly detected_at: string;
};

/**
 * * `low` - Low
 * * `medium` - Medium
 * * `high` - High
 */
export type RelayAnomalySeverityEnum = 'low' | 'medium' | 'high';

/**
 * * `username` - Username Search
 * * `domain` - Domain Attack Surface
 * * `metadata` - Document OpSec Analyzer
 * * `tor_relay` - Tor Network Anomaly
 */
export type ScanTypeEnum = 'username' | 'domain' | 'metadata' | 'tor_relay';

export type SearchRequest = {
    query: string;
    top_k?: number;
};

export type Snapshot = {
    readonly id: number;
    source_type: SourceTypeEnum;
    target: string;
    content_hash: string;
    changed?: boolean;
    diff?: unknown;
    monitored_target?: number | null;
    osint_scan?: number | null;
    darkweb_crawl?: number | null;
    previous?: number | null;
    readonly created_at: string;
};

export type Source = {
    readonly id: number;
    kind?: SourceKindEnum;
    value: string;
    tags?: unknown;
    metadata?: unknown;
    readonly created_at: string;
};

/**
 * * `url` - URL
 * * `search` - Search
 * * `manual` - Manual
 */
export type SourceKindEnum = 'url' | 'search' | 'manual';

/**
 * * `username` - Username scan
 * * `crawl` - Web crawl
 */
export type SourceTypeEnum = 'username' | 'crawl';

export type SummarizeRequest = {
    text?: string;
    document_ids?: Array<number>;
    prompt?: string;
};

export type SummarizeResponse = {
    summary: string;
    provider: string;
    model: string;
    metadata: {
        [key: string]: unknown;
    };
};

export type AlertEventWritable = {
    rule?: number | null;
    monitored_target?: number | null;
    event_type: EventTypeEnum;
    severity?: AlertEventSeverityEnum;
    title: string;
    message: string;
    payload?: unknown;
    delivered?: boolean;
};

export type AlertRuleWritable = {
    name: string;
    event_type: EventTypeEnum;
    conditions?: unknown;
    enabled?: boolean;
    monitored_target?: number | null;
    cooldown_minutes?: number;
};

export type CensorshipIncidentWritable = {
    country_code: string;
    asn: string;
    target_domain: string;
    anomaly_type: string;
    measurement_count?: number;
    failure_rate?: number;
};

export type DarkWebCrawlWritable = {
    url: string;
    keywords?: string;
};

export type DocumentWritable = {
    url?: string | string;
    title?: string;
    content_markdown?: string;
    metadata?: unknown;
    embedding_id?: string;
};

export type IngestionJobWritable = {
    status?: ProcessingStatusEnum;
    provider_preference?: unknown;
    tags?: unknown;
    notification_settings?: unknown;
    error?: string;
    cost_metadata?: unknown;
    result_metadata?: unknown;
    completed_at?: string | null;
};

export type JobTargetWritable = {
    url: string;
    status?: JobTargetStatusEnum;
    fetched_with?: string;
    error?: string;
};

export type MonitoredTargetWritable = {
    kind: MonitoredTargetKindEnum;
    value: string;
    /**
     * Seconds between scheduled checks.
     */
    interval?: number;
    enabled?: boolean;
    config?: unknown;
};

export type OsintScanWritable = {
    target: string;
    scan_type: ScanTypeEnum;
};

export type PatchedAlertRuleWritable = {
    name?: string;
    event_type?: EventTypeEnum;
    conditions?: unknown;
    enabled?: boolean;
    monitored_target?: number | null;
    cooldown_minutes?: number;
};

export type PatchedDarkWebCrawlWritable = {
    url?: string;
    keywords?: string;
};

export type PatchedMonitoredTargetWritable = {
    kind?: MonitoredTargetKindEnum;
    value?: string;
    /**
     * Seconds between scheduled checks.
     */
    interval?: number;
    enabled?: boolean;
    config?: unknown;
};

export type PatchedOsintScanWritable = {
    target?: string;
    scan_type?: ScanTypeEnum;
};

export type RelayAnomalyWritable = {
    fingerprint: string;
    nickname?: string;
    country_code?: string;
    country_name?: string;
    as_number?: string;
    latitude?: number | null;
    longitude?: number | null;
    metric?: string;
    anomaly_type?: string;
    score?: number;
    severity?: RelayAnomalySeverityEnum;
    detector?: string;
    detail?: unknown;
};

export type SnapshotWritable = {
    source_type: SourceTypeEnum;
    target: string;
    content_hash: string;
    changed?: boolean;
    diff?: unknown;
    monitored_target?: number | null;
    osint_scan?: number | null;
    darkweb_crawl?: number | null;
    previous?: number | null;
};

export type SourceWritable = {
    kind?: SourceKindEnum;
    value: string;
    tags?: unknown;
    metadata?: unknown;
};

export type AiStatusRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ai/status';
};

export type AiStatusRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type AiStatusRetrieveResponse = AiStatusRetrieveResponses[keyof AiStatusRetrieveResponses];

export type AiSummarizeCreateData = {
    body?: SummarizeRequest;
    path?: never;
    query?: never;
    url: '/api/ai/summarize';
};

export type AiSummarizeCreateResponses = {
    200: SummarizeResponse;
};

export type AiSummarizeCreateResponse = AiSummarizeCreateResponses[keyof AiSummarizeCreateResponses];

export type HealthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type HealthRetrieveResponse = HealthRetrieveResponses[keyof HealthRetrieveResponses];

export type JobsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs/';
};

export type JobsListResponses = {
    200: Array<IngestionJob>;
};

export type JobsListResponse = JobsListResponses[keyof JobsListResponses];

export type JobsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/jobs/{id}';
};

export type JobsRetrieveResponses = {
    200: IngestionJob;
};

export type JobsRetrieveResponse = JobsRetrieveResponses[keyof JobsRetrieveResponses];

export type JobsIngestData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/api/jobs/ingest';
};

export type JobsIngestResponses = {
    201: IngestionJob;
};

export type JobsIngestResponse = JobsIngestResponses[keyof JobsIngestResponses];

export type OsintAlertEventsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/alert-events/';
};

export type OsintAlertEventsListResponses = {
    200: Array<AlertEvent>;
};

export type OsintAlertEventsListResponse = OsintAlertEventsListResponses[keyof OsintAlertEventsListResponses];

export type OsintAlertEventsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this alert event.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/alert-events/{id}/';
};

export type OsintAlertEventsRetrieveResponses = {
    200: AlertEvent;
};

export type OsintAlertEventsRetrieveResponse = OsintAlertEventsRetrieveResponses[keyof OsintAlertEventsRetrieveResponses];

export type OsintAlertRulesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/alert-rules/';
};

export type OsintAlertRulesListResponses = {
    200: Array<AlertRule>;
};

export type OsintAlertRulesListResponse = OsintAlertRulesListResponses[keyof OsintAlertRulesListResponses];

export type OsintAlertRulesCreateData = {
    body: AlertRuleWritable;
    path?: never;
    query?: never;
    url: '/api/osint/alert-rules/';
};

export type OsintAlertRulesCreateResponses = {
    201: AlertRule;
};

export type OsintAlertRulesCreateResponse = OsintAlertRulesCreateResponses[keyof OsintAlertRulesCreateResponses];

export type OsintAlertRulesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this alert rule.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/alert-rules/{id}/';
};

export type OsintAlertRulesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OsintAlertRulesDestroyResponse = OsintAlertRulesDestroyResponses[keyof OsintAlertRulesDestroyResponses];

export type OsintAlertRulesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this alert rule.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/alert-rules/{id}/';
};

export type OsintAlertRulesRetrieveResponses = {
    200: AlertRule;
};

export type OsintAlertRulesRetrieveResponse = OsintAlertRulesRetrieveResponses[keyof OsintAlertRulesRetrieveResponses];

export type OsintAlertRulesPartialUpdateData = {
    body?: PatchedAlertRuleWritable;
    path: {
        /**
         * A unique integer value identifying this alert rule.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/alert-rules/{id}/';
};

export type OsintAlertRulesPartialUpdateResponses = {
    200: AlertRule;
};

export type OsintAlertRulesPartialUpdateResponse = OsintAlertRulesPartialUpdateResponses[keyof OsintAlertRulesPartialUpdateResponses];

export type OsintAlertRulesUpdateData = {
    body: AlertRuleWritable;
    path: {
        /**
         * A unique integer value identifying this alert rule.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/alert-rules/{id}/';
};

export type OsintAlertRulesUpdateResponses = {
    200: AlertRule;
};

export type OsintAlertRulesUpdateResponse = OsintAlertRulesUpdateResponses[keyof OsintAlertRulesUpdateResponses];

export type OsintAnomaliesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/anomalies/';
};

export type OsintAnomaliesListResponses = {
    200: Array<RelayAnomaly>;
};

export type OsintAnomaliesListResponse = OsintAnomaliesListResponses[keyof OsintAnomaliesListResponses];

export type OsintAnomaliesCreateData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/osint/anomalies/';
};

export type OsintAnomaliesCreateResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type OsintAnomaliesCreateResponse = OsintAnomaliesCreateResponses[keyof OsintAnomaliesCreateResponses];

export type OsintCensorshipListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/censorship/';
};

export type OsintCensorshipListResponses = {
    200: Array<CensorshipIncident>;
};

export type OsintCensorshipListResponse = OsintCensorshipListResponses[keyof OsintCensorshipListResponses];

export type OsintCrawlListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/crawl/';
};

export type OsintCrawlListResponses = {
    200: Array<DarkWebCrawl>;
};

export type OsintCrawlListResponse = OsintCrawlListResponses[keyof OsintCrawlListResponses];

export type OsintCrawlCreateData = {
    body: DarkWebCrawlWritable;
    path?: never;
    query?: never;
    url: '/api/osint/crawl/';
};

export type OsintCrawlCreateResponses = {
    201: DarkWebCrawl;
};

export type OsintCrawlCreateResponse = OsintCrawlCreateResponses[keyof OsintCrawlCreateResponses];

export type OsintCrawlDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this dark web crawl.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/crawl/{id}/';
};

export type OsintCrawlDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OsintCrawlDestroyResponse = OsintCrawlDestroyResponses[keyof OsintCrawlDestroyResponses];

export type OsintCrawlRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this dark web crawl.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/crawl/{id}/';
};

export type OsintCrawlRetrieveResponses = {
    200: DarkWebCrawl;
};

export type OsintCrawlRetrieveResponse = OsintCrawlRetrieveResponses[keyof OsintCrawlRetrieveResponses];

export type OsintCrawlPartialUpdateData = {
    body?: PatchedDarkWebCrawlWritable;
    path: {
        /**
         * A unique integer value identifying this dark web crawl.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/crawl/{id}/';
};

export type OsintCrawlPartialUpdateResponses = {
    200: DarkWebCrawl;
};

export type OsintCrawlPartialUpdateResponse = OsintCrawlPartialUpdateResponses[keyof OsintCrawlPartialUpdateResponses];

export type OsintCrawlUpdateData = {
    body: DarkWebCrawlWritable;
    path: {
        /**
         * A unique integer value identifying this dark web crawl.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/crawl/{id}/';
};

export type OsintCrawlUpdateResponses = {
    200: DarkWebCrawl;
};

export type OsintCrawlUpdateResponse = OsintCrawlUpdateResponses[keyof OsintCrawlUpdateResponses];

export type OsintMonitorsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/monitors/';
};

export type OsintMonitorsListResponses = {
    200: Array<MonitoredTarget>;
};

export type OsintMonitorsListResponse = OsintMonitorsListResponses[keyof OsintMonitorsListResponses];

export type OsintMonitorsCreateData = {
    body: MonitoredTargetWritable;
    path?: never;
    query?: never;
    url: '/api/osint/monitors/';
};

export type OsintMonitorsCreateResponses = {
    201: MonitoredTarget;
};

export type OsintMonitorsCreateResponse = OsintMonitorsCreateResponses[keyof OsintMonitorsCreateResponses];

export type OsintMonitorsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this monitored target.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/monitors/{id}/';
};

export type OsintMonitorsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OsintMonitorsDestroyResponse = OsintMonitorsDestroyResponses[keyof OsintMonitorsDestroyResponses];

export type OsintMonitorsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this monitored target.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/monitors/{id}/';
};

export type OsintMonitorsRetrieveResponses = {
    200: MonitoredTarget;
};

export type OsintMonitorsRetrieveResponse = OsintMonitorsRetrieveResponses[keyof OsintMonitorsRetrieveResponses];

export type OsintMonitorsPartialUpdateData = {
    body?: PatchedMonitoredTargetWritable;
    path: {
        /**
         * A unique integer value identifying this monitored target.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/monitors/{id}/';
};

export type OsintMonitorsPartialUpdateResponses = {
    200: MonitoredTarget;
};

export type OsintMonitorsPartialUpdateResponse = OsintMonitorsPartialUpdateResponses[keyof OsintMonitorsPartialUpdateResponses];

export type OsintMonitorsUpdateData = {
    body: MonitoredTargetWritable;
    path: {
        /**
         * A unique integer value identifying this monitored target.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/monitors/{id}/';
};

export type OsintMonitorsUpdateResponses = {
    200: MonitoredTarget;
};

export type OsintMonitorsUpdateResponse = OsintMonitorsUpdateResponses[keyof OsintMonitorsUpdateResponses];

export type OsintMonitorsRunCreateData = {
    body: MonitoredTargetWritable;
    path: {
        /**
         * A unique integer value identifying this monitored target.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/monitors/{id}/run/';
};

export type OsintMonitorsRunCreateResponses = {
    200: MonitoredTarget;
};

export type OsintMonitorsRunCreateResponse = OsintMonitorsRunCreateResponses[keyof OsintMonitorsRunCreateResponses];

export type OsintScanListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/scan/';
};

export type OsintScanListResponses = {
    200: Array<OsintScan>;
};

export type OsintScanListResponse = OsintScanListResponses[keyof OsintScanListResponses];

export type OsintScanCreateData = {
    body: OsintScanWritable;
    path?: never;
    query?: never;
    url: '/api/osint/scan/';
};

export type OsintScanCreateResponses = {
    201: OsintScan;
};

export type OsintScanCreateResponse = OsintScanCreateResponses[keyof OsintScanCreateResponses];

export type OsintScanDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this osint scan.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/scan/{id}/';
};

export type OsintScanDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OsintScanDestroyResponse = OsintScanDestroyResponses[keyof OsintScanDestroyResponses];

export type OsintScanRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this osint scan.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/scan/{id}/';
};

export type OsintScanRetrieveResponses = {
    200: OsintScan;
};

export type OsintScanRetrieveResponse = OsintScanRetrieveResponses[keyof OsintScanRetrieveResponses];

export type OsintScanPartialUpdateData = {
    body?: PatchedOsintScanWritable;
    path: {
        /**
         * A unique integer value identifying this osint scan.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/scan/{id}/';
};

export type OsintScanPartialUpdateResponses = {
    200: OsintScan;
};

export type OsintScanPartialUpdateResponse = OsintScanPartialUpdateResponses[keyof OsintScanPartialUpdateResponses];

export type OsintScanUpdateData = {
    body: OsintScanWritable;
    path: {
        /**
         * A unique integer value identifying this osint scan.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/scan/{id}/';
};

export type OsintScanUpdateResponses = {
    200: OsintScan;
};

export type OsintScanUpdateResponse = OsintScanUpdateResponses[keyof OsintScanUpdateResponses];

export type OsintSnapshotsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/osint/snapshots/';
};

export type OsintSnapshotsListResponses = {
    200: Array<Snapshot>;
};

export type OsintSnapshotsListResponse = OsintSnapshotsListResponses[keyof OsintSnapshotsListResponses];

export type OsintSnapshotsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this snapshot.
         */
        id: number;
    };
    query?: never;
    url: '/api/osint/snapshots/{id}/';
};

export type OsintSnapshotsRetrieveResponses = {
    200: Snapshot;
};

export type OsintSnapshotsRetrieveResponse = OsintSnapshotsRetrieveResponses[keyof OsintSnapshotsRetrieveResponses];

export type SearchCreateData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/search';
};

export type SearchCreateResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SearchCreateResponse = SearchCreateResponses[keyof SearchCreateResponses];

export type TelegramWebhookCreateData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/telegram/webhook';
};

export type TelegramWebhookCreateResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type TelegramWebhookCreateResponse = TelegramWebhookCreateResponses[keyof TelegramWebhookCreateResponses];
