# Generated by Django 5.2.15 on 2026-07-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensorshipIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=8)),
                ('asn', models.CharField(max_length=32)),
                ('target_domain', models.CharField(max_length=512)),
                ('anomaly_type', models.CharField(max_length=128)),
                ('measurement_count', models.IntegerField(default=1)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='OSINTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512)),
                ('scan_type', models.CharField(choices=[('username', 'Username Search'), ('domain', 'Domain Attack Surface'), ('metadata', 'Document OpSec Analyzer'), ('tor_relay', 'Tor Network Anomaly')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='osint_osint_status_f1b0cf_idx'), models.Index(fields=['scan_type'], name='osint_osint_scan_ty_d80343_idx')],
            },
        ),
    ]
