# Generated by Django 5.2.15 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkWebCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('keywords', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('routed_via_tor', models.BooleanField(default=False)),
                ('is_onion', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelayAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('country_name', models.CharField(blank=True, max_length=64)),
                ('as_number', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metric', models.CharField(default='observed_bandwidth', max_length=32)),
                ('anomaly_type', models.CharField(default='bandwidth_spike', max_length=64)),
                ('score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=8)),
                ('detector', models.CharField(default='TimeSeriesOD', max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-detected_at'],
                'indexes': [models.Index(fields=['severity'], name='osint_relay_severit_8b0853_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelayObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('country_name', models.CharField(blank=True, max_length=64)),
                ('as_number', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('observed_bandwidth', models.BigIntegerField(default=0)),
                ('consensus_weight', models.BigIntegerField(default=0)),
                ('running', models.BooleanField(default=True)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['fingerprint', 'observed_at'],
                'indexes': [models.Index(fields=['fingerprint', 'observed_at'], name='osint_relay_fingerp_55182e_idx')],
            },
        ),
    ]
