# Generated by Django 5.2.15 on 2026-07-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0002_darkwebcrawl_relayanomaly_relayobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('username', 'Username'), ('domain', 'Domain'), ('ooni', 'OONI domain'), ('tor_relay', 'Tor relay'), ('onion', 'Onion URL')], max_length=24)),
                ('value', models.CharField(max_length=1024)),
                ('interval', models.PositiveIntegerField(default=3600, help_text='Seconds between scheduled checks.')),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'value'],
                'indexes': [models.Index(fields=['enabled', 'last_run'], name='osint_monit_enabled_173432_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_monitored_target')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('relay_anomaly', 'Relay anomaly'), ('censorship', 'Censorship incident'), ('keyword_hit', 'Crawler keyword hit'), ('change', 'Snapshot change')], max_length=24)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitored_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='osint.monitoredtarget')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='darkwebcrawl',
            name='monitored_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawls', to='osint.monitoredtarget'),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='monitored_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='osint.monitoredtarget'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('relay_anomaly', 'Relay anomaly'), ('censorship', 'Censorship incident'), ('keyword_hit', 'Crawler keyword hit'), ('change', 'Snapshot change')], max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=8)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='osint.alertrule')),
                ('monitored_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='osint.monitoredtarget')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='osint_alert_event_t_d33200_idx'), models.Index(fields=['delivered', 'created_at'], name='osint_alert_deliver_d944e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('username', 'Username scan'), ('crawl', 'Web crawl')], max_length=24)),
                ('target', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('changed', models.BooleanField(default=False)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('darkweb_crawl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='osint.darkwebcrawl')),
                ('monitored_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='osint.monitoredtarget')),
                ('osint_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='osint.osintscan')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_snapshots', to='osint.snapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'target', 'created_at'], name='osint_snaps_source__46bedd_idx')],
            },
        ),
    ]
