# Generated by Django 5.2.15 on 2026-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0003_monitoredtarget_alertrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='event_type',
            field=models.CharField(choices=[('relay_anomaly', 'Relay anomaly'), ('censorship', 'Censorship incident'), ('keyword_hit', 'Crawler keyword hit'), ('change', 'Snapshot change'), ('drug_signal', 'Drug-intelligence signal')], max_length=24),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='event_type',
            field=models.CharField(choices=[('relay_anomaly', 'Relay anomaly'), ('censorship', 'Censorship incident'), ('keyword_hit', 'Crawler keyword hit'), ('change', 'Snapshot change'), ('drug_signal', 'Drug-intelligence signal')], max_length=24),
        ),
    ]
