# Generated by Django 5.2.15 on 2026-07-05 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('provider_preference', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notification_settings', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('cost_metadata', models.JSONField(blank=True, default=dict)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_ingest_status_79cdb7_idx'), models.Index(fields=['created_at'], name='jobs_ingest_created_af892b_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetched', 'Fetched'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('fetched_with', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_targets', to='sources.document')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='jobs.ingestionjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
