# Generated by Django 5.2.15 on 2026-08-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('authorization_reference', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUpdateReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(default='received', max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('telegram_channel', 'Telegram channel'), ('telegram_handle', 'Telegram handle'), ('url', 'URL'), ('onion', 'Onion address'), ('domain', 'Domain'), ('contact', 'Contact indicator')], max_length=32)),
                ('value', models.CharField(max_length=1024)),
                ('normalized_value', models.CharField(max_length=1024)),
                ('display_name', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'normalized_value'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'normalized_value'), name='unique_entity_kind_normalized_value')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('onion', 'Onion service'), ('manual', 'Manual evidence')], default='telegram', max_length=24)),
                ('external_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=256)),
                ('public_url', models.URLField(blank=True, max_length=1024)),
                ('collection_mode', models.CharField(choices=[('bot_webhook', 'Telegram Bot webhook'), ('approved_public', 'Approved public source'), ('manual', 'Manual import')], default='bot_webhook', max_length=32)),
                ('authorization_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('interval', models.PositiveIntegerField(default=3600)),
                ('latest_cursor', models.CharField(blank=True, max_length=128)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='drugintel.investigation')),
            ],
            options={
                'ordering': ['platform', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('telegram_message', 'Telegram message'), ('onion_crawl', 'Onion crawl'), ('manual', 'Manual evidence')], default='telegram_message', max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author_alias', models.CharField(blank=True, max_length=256)),
                ('reply_to_external_id', models.CharField(blank=True, max_length=128)),
                ('forwarded_from', models.CharField(blank=True, max_length=256)),
                ('public_url', models.URLField(blank=True, max_length=1024)),
                ('content', models.TextField(blank=True)),
                ('normalized_content', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='drugintel.intelligencesource')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='drugintel.investigation')),
            ],
            options={
                'ordering': ['-occurred_at', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('illicit_sale', 'Potential illicit drug sale'), ('controlled_substance', 'Controlled substance reference')], max_length=32)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('evidence_spans', models.JSONField(blank=True, default=list)),
                ('rule_version', models.CharField(default='drug-intel-rules-v1', max_length=64)),
                ('review_status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('corroborated', 'Corroborated'), ('false_positive', 'False positive'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='new', max_length=24)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='drugintel.evidenceitem')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='drugintel.investigation')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('supporting_evidence_ids', models.JSONField(blank=True, default=list)),
                ('entity_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='drugintel.investigation')),
            ],
            options={
                'ordering': ['-updated_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('corroborated', 'Corroborated'), ('false_positive', 'False positive'), ('escalated', 'Escalated'), ('closed', 'Closed')], max_length=24)),
                ('reviewer', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='drugintel.drugsignal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='mentioned', max_length=64)),
                ('evidence_span', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='drugintel.entity')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='drugintel.evidenceitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evidence', 'entity', 'role'), name='unique_evidence_entity_role')],
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='drugintel.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='drugintel.entity')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='drugintel.evidenceitem')),
            ],
            options={
                'indexes': [models.Index(fields=['relationship_type', 'created_at'], name='drugintel_e_relatio_16c080_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencesource',
            index=models.Index(fields=['enabled', 'authorization_status', 'last_collected_at'], name='drugintel_i_enabled_12aae4_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencesource',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_intel_source_platform_external_id'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['source', 'external_id', 'is_latest'], name='drugintel_e_source__e0f65b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['investigation', 'occurred_at'], name='drugintel_e_investi_db8405_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['content_hash'], name='drugintel_e_content_26db12_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceitem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id', 'version'), name='unique_evidence_source_external_version'),
        ),
        migrations.AddIndex(
            model_name='drugsignal',
            index=models.Index(fields=['review_status', 'risk_score'], name='drugintel_d_review__df0b43_idx'),
        ),
        migrations.AddIndex(
            model_name='drugsignal',
            index=models.Index(fields=['investigation', 'created_at'], name='drugintel_d_investi_0986db_idx'),
        ),
    ]
